language: node_js
node_js:
  - 8
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run lint
  - npm run test
deploy:
  provider: firebase
  token:
    secure: '...'
  skip_cleanup: true